import android.app.AlertDialog
import android.content.Context
import android.os.Handler
import android.os.Looper
import android.view.LayoutInflater
import android.view.View
import android.widget.PopupWindow
import com.example.griffinmobile.R
import com.example.griffinmobile.mudels.Thermostst
import com.example.griffinmobile.mudels.udp_thermostat_for_scenario
